---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  password: "<your-password-here>"
  username: "<your-username-here>"
  database: "<your-database-here>"
...
