apiVersion: v1
kind: Service
metadata:
  name: node-service
  labels:
    type: service
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30006
  selector:
    type: result-app
...
