---
apiVersion: v1
kind: Service
metadata:
  name: python-service
  labels:
    type: service
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30005
  selector:
    type: voting-app
...
