apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    type: service
spec:
  type: ClusterIP
  ports:
    - targetPort: 6379
      port: 6379
  selector:
    type: in-memory-db
...
